---
abstract: 'Small dispatcher with Regular-Expression'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dispatcher-Small
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Dispatcher::Small:
    file: lib/Dispatcher/Small.pm
    version: 0.01
requires:
  perl: 5.010
resources:
  bugtracker: https://github.com/ytnobody/Dispatcher-Small/issues
  homepage: https://github.com/ytnobody/Dispatcher-Small
  repository: git://github.com/ytnobody/Dispatcher-Small.git
version: 0.01
